name: Aprende a usar Expresiones

on: [push]

jobs:
  probar-expresiones:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # Expresión 1: Usuario que lanza el flujo
      - name: Mostrar el usuario que lanzó el flujo
        run: echo "El flujo fue iniciado por la expresión ${{ github.actor }}"

      # Expresión 2: Tipo de evento
      - name: Mostrar el tipo de evento
        run: echo "Este flujo se ejecutó por un evento de tipo ${{ github.event_name }}"

      # Expresión 3: Condicional
      - name: Paso condicional con expresiones
        if: ${{ success() }}
        run: echo "Este paso se ejecuta solo si los pasos anteriores tuvieron éxito"
