name: Aprende a usar los distintos Contextos

on: [push]

jobs:
  probar-contextos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v7

      # 1. Usando el contexto 'github' para ver detalles del repositorio remoto
      - name: Mostrar información del repositorio
        run: |
          echo "El repositorio actual es: ${{ github.repository }}"
          echo "La rama que ejecutó esto es: ${{ github.ref_name }}"

      # 2. Usando el contexto 'runner' para ver detalles de la máquina virtual que corre el código
      - name: Mostrar detalles del entorno del Runner
        run: |
          echo "El sistema operativo del servidor es: ${{ runner.os }}"
          echo "La arquitectura del procesador es: ${{ runner.arch }}"

      # 3. Usando el contexto 'job' para ver el estado actual del trabajo
      - name: Mostrar estado del Job
        run: echo "El ID de este trabajo en ejecución es ${{ github.job }}"
