name: Paso 5, Aprende a usar las Variables de Entorno

on: [push]

# 1. Definimos una variable de entorno a nivel global
env:
  CURSO: "GitHub Actions en Platzi"

jobs:
  probar-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Usamos la variable de entorno global usando la sintaxis $nombre_variable o ${{ env.nombre }}
      - name: Mostrar variable global
        run: echo "Estamos completando el curso de $CURSO"

      # 3. Definimos y usamos una variable de entorno local (solo sirve para este paso/trabajo)
      - name: Mostrar variable local
        env:
          ESTUDIANTE: "Luis"
        run: echo "Felicidades $ESTUDIANTE, has llegado al final del taller básico."
